### ISSUE TITLE
401 Errors from Rinnai APIs

### ISSUE THREAD

**Issue by dustindclark** [dustindclark/homebridge-rinnai-controlr#11]
Same error reported on HA: https://github.com/explosivo22/rinnaicontrolr/issues/13

Logs:

```
[10/1/2022, 5:42:13 PM] [homebridge-rinnai-controlr] Could not poll Rinnai devices {
  data: {},
  errors: [
    Error: Request failed with status code 401
        at createError (/usr/lib/node_modules/homebridge-rinnai-controlr/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/usr/lib/node_modules/homebridge-rinnai-controlr/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-rinnai-controlr/node_modules/axios/lib/adapters/http.js:322:11)
        at IncomingMessage.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1358:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by guillochon** [comment]
I am also having connection problems, except it appears my username is no longer valid:

```
[02/10/2022, 10:05:40] [RinnaiControlR] setRecirculateActive to true for device null
[02/10/2022, 10:05:40] [RinnaiControlR] Caught error setting state. No current user
```

When I go to the Rinnai website to try to log in, it says my username/password is not valid. When I try to reset my password, I never get a password reset email. Lastly, the Control-R iOS app has removed the heater from my account, and if I log out there I cannot log back in.

So I think this all might be on Rinnai's side? I was going to give tech support a call tomorrow morning.

**Comment by wrmacj** [comment]
I have the same problem and also cannot logon to the ControlR app.  I got the msg that indicated that password was invalid and did a password reset.  When I went to logon to ControlR it required a complete ControlR setup. 
The ControlR setup does not complete, 
It looks to bwe a Rinnai issue.

**Comment by guillochon** [comment]
So while I am able to connect again, and this plugin doesn't spit out any errors anymore, my water heater seems to be perpetually in "recirculation" mode. In the Control-R app it always shows as "recirculating" and in Apple Home the device's status is always on. If I send an off command, the Home accessory shows as off for a little bit (maybe 10ish seconds), but immediately flips back on. Anyone else seeing this behavior recently?

**Comment by dustindclark** [comment]
The previous 401 issue was a Rinnai outage over the weekend (see related ticket in initial post).

@guillochon let's create a new issue for this. Please post the logs you're seeing on Homebridge startup and when you attempt to toggle recirc.
